---
# tasks file for check_updates
- name: Verifica atualizações disponíveis
  win_updates:
    category_names: "*"
    state: searched
  register: available_updates

- name: Lista atualizações disponíveis 
  debug:
    msg: |
      O host {{ inventory_hostname }} tem {{ available_updates.found_update_count }} atualizações disponíves.
      {% for update in updates %}
        - {{ update.title }}
      {% endfor %}
  vars:
    updates: "{{ (available_updates.updates.values() | list) if (available_updates.updates is mapping) else (available_updates.updates) }}"
  when: available_updates.updates is defined